---
driver:
  name: vagrant
driver_config:
  # allow vagrant-cachier to cache chef omnibus package, see https://github.com/test-kitchen/test-kitchen/issues/440
  require_chef_omnibus: true
  chef_omnibus_url: https://www.getchef.com/chef/install.sh -d /tmp/vagrant-cache/vagrant_omnibus

  use_vagrant_berkshelf_plugin: true
  customize:
    memory: 2048
    cpus: 2
  network:
      # Allow access to the Jenkins webui which is useful when troubleshooting
      - - forwarded_port
        - guest: 8080
          host: 8080
          auto_correct: true

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    data_bags_path: 'test/integration/default/data_bags'
    run_list:
      - recipe[camunda-ci-jenkins::user]
      - recipe[camunda-ci-jenkins::default]
    attributes: {}
  - name: docker
    data_bags_path: 'test/integration/default/data_bags'
    run_list:
      - recipe[docker::default]
      - recipe[camunda-ci-jenkins::user]
      - recipe[camunda-ci-jenkins::default]
    attributes:
      {
        docker: {
          host: ['127.0.0.1:2375', 'unix:///var/run/docker.sock'],
        }
      }
